### ISSUE TITLE
Trough recipe gives Treated Acacia Planks instead

### ISSUE THREAD

**Issue by mintynoura** [lumiscosity/rounded#2]
hi! the issue is pretty minor and easily fixed, i just happened upon it when i was checking recipes in my modpack

screenshot using emi: 
![image](https://github.com/user-attachments/assets/1985b9ec-1862-4220-9433-c5943d124dd6)

present in the json:
https://github.com/lumiscosity/rounded/blob/main/src/main/resources/data/rounded/recipe/trough.json

**Comment by lumiscosity** [comment]
add that to the simple one-liner bugs...

fixed by latest commit! it'll be in release 1.0.4 later today

**Comment by lumiscosity** [comment]
(update about this; i'm pushing the release of 1.0.4 to tommorow, i'll be adding a bunch of mod compat and i want to have some time to test it)

**Comment by mintynoura** [comment]
thank you for your hard work!!

**Comment by lumiscosity** [comment]
1.0.4 is out now for 1.20.1, 1.21 version coming up soon
